"use client";

import React from "react";
import Head from "next/head";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import HousePersonTreeTest from "../components/HousePersonTreeTest";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import dynamic from "next/dynamic";

const FloatingEmotionDetection = dynamic(
  () => import("../components/new-emotion-detection/FloatingEmotionDetection"),
  { ssr: false },
);

export default function HPTTestPage() {
  return (
    <div className="min-h-screen flex flex-col flex-auto flex-shrink-0 antialiased bg-white dark:bg-gray-900 text-black dark:text-white">
      <Head>
        <script
          src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.8.0/dist/alpine.min.js"
          defer
        ></script>
      </Head>
      <Header />
      <Sidebar />
      <div className="ml-14 mt-14 mb-10 md:ml-64">
        <div className="bg-gray-50 dark:bg-gray-800 p-6 rounded-lg shadow">
          <div className="max-w-3xl mx-auto mb-8 text-center">
            <h1 className="text-3xl font-bold mb-4 text-gray-900 dark:text-white">House-Person-Tree (H-P-T) Test</h1>
            <p className="text-gray-600 dark:text-gray-300">
              The House-Person-Tree test is a projective psychological assessment that can reveal aspects of your personality, emotional state, and interpersonal dynamics through your drawings.
            </p>
            <div className="mt-4 text-sm text-gray-500 dark:text-gray-400 p-4 bg-gray-100 dark:bg-gray-700 rounded-lg">
              <p className="font-medium mb-2">Instructions:</p>
              <ul className="list-disc list-inside space-y-1">
                <li>You will be asked to draw three things: a house, a person, and a tree</li>
                <li>Draw each item as completely as you can - take your time</li>
                <li>There are no right or wrong ways to draw - express yourself naturally</li>
                <li>After completing all drawings, AI analysis will provide psychological insights</li>
                <li>Your drawings are saved securely and are only visible to you</li>
              </ul>
            </div>
          </div>

          <div className="mt-4 p-4 bg-yellow-50 dark:bg-yellow-900 border-l-4 border-yellow-400 text-yellow-800 dark:text-yellow-100 rounded">
              <p className="font-medium mb-1">Disclaimer:</p>
              <p className="text-sm">
                This is a prototype for thesis research purposes. The analysis is generated by AI and should not be considered 
                a clinical psychological assessment. For professional evaluation, please consult with a licensed mental health professional.
              </p>
            </div>
          
          <HousePersonTreeTest />
        </div>
      </div>
      <FloatingEmotionDetection />
      <ToastContainer />
    </div>
  );
}